# Generated by Django 2.0.6 on 2018-11-07 22:26

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product code')),
                ('brand', models.CharField(default=None, max_length=20, verbose_name='Brand')),
                ('category', models.CharField(default=None, max_length=30, verbose_name='Category')),
                ('description', models.CharField(default=None, max_length=100, verbose_name='Description')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Purchase price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Selling price')),
                ('size', models.CharField(default=None, max_length=5, verbose_name='Size')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('image', models.FileField(blank=True, default=None, upload_to=stock.models.save_directory_path, verbose_name='Picture')),
                ('sold', models.BooleanField(default=False, verbose_name='Sold')),
            ],
            options={
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
