# Generated by Django 2.0.6 on 2018-12-08 16:56

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('brand', models.CharField(default=None, max_length=20, verbose_name='Бренд')),
                ('category', models.CharField(default=None, max_length=30, verbose_name='Категория')),
                ('description', models.CharField(default=None, max_length=100, verbose_name='Описание')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Закупочная цена')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена продажи')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка')),
                ('size', models.CharField(default=None, max_length=5, verbose_name='Размер')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('image', models.FileField(blank=True, default=None, upload_to=stock.models.save_directory_path, verbose_name='Фото')),
                ('sold', models.BooleanField(default=False, verbose_name='Продано')),
            ],
            options={
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
