# Generated by Django 2.0.6 on 2018-11-09 12:49

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.CharField(default=None, max_length=20, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.CharField(default=None, max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(default=None, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=stock.models.save_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(default=None, max_length=5, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
