# Generated by Django 2.0.6 on 2018-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181109_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка'),
        ),
    ]
