# Generated by Django 2.0.6 on 2018-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20181127_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
