# Generated by Django 2.0.6 on 2018-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Расход за день')),
                ('purpose', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Назначение')),
            ],
            options={
                'verbose_name_plural': 'Expences',
            },
        ),
    ]
